name: Release to WoW Interface

env:
  ADDON_NAME: Broker_DungeonDifficulty
  ADDON_BUNDLE_FILES: libs/ Broker_DungeonDifficulty.lua lib.lua LICENSE README.md
  WOWI_ID: 25712

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Create 'dist' folder
      run: mkdir ${{env.ADDON_NAME}}/

    - name: Put everything into a folder
      run: cp ${{ env.ADDON_BUNDLE_FILES }} ${{ env.ADDON_NAME }}.toc ${{env.ADDON_NAME}}/
  
    - name: Zip it good
      run: zip -9 -r ${{env.ADDON_NAME}}.zip  ${{env.ADDON_NAME}}/
      
#     - name: What is here (for debugging)
#       run: ls -lsa
      
    - name: Parse WoW Addon Verions
      id: get_versions
      uses: icbat/parse-wow-addon-version@v0.0.1
      with:
        tocfile: ${{ env.ADDON_NAME }}.toc
    
    - name: Upload to WoW Interface
      uses: icbat/wow-addon-upload-action@v0.0.4
      with:
        id: ${{ env.WOWI_ID }}
        zipFilePath: ${{ env.ADDON_NAME }}.zip
        compatible: ${{ steps.get_versions.outputs.supported_version }}
        version: ${{ steps.get_versions.outputs.addon_version }}
        apiKey: ${{ secrets.WOW_INTERFACE }}
