name: Release new version of addon

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Package and Upload to all the places 
        uses: BigWigsMods/packager@v2
        env:
          WAGO_API_TOKEN: ${{secrets.WAGO_API_TOKEN}}
          WOWI_API_TOKEN: ${{secrets.WOWI_API_TOKEN}}
          GITHUB_OAUTH:   ${{secrets.GITHUB_TOKEN}}

