name: Release to WoW Interface

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
  
    - name: Zip it good
      run: zip -9 -r Broker_DungeonDifficulty.zip libs/ Broker_DungeonDifficulty.lua Broker.lua Display.lua Localization.lua Broker_DungeonDifficulty.toc LICENSE README.md
      
#     - name: What is here (for debugging)
#       run: ls -lsa
      
    - name: Parse WoW Addon Verions
      id: get_versions
      uses: icbat/parse-wow-addon-version@v0.0.1
      with:
        tocfile:  Broker_DungeonDifficulty.toc
    
#     - name: Echo Verisons
#       run: echo ${{ steps.get_versions.outputs.supported_version }} ${{ steps.get_versions.outputs.addon_version }}

    - name: Upload to WoW Interface
      uses: icbat/wow-addon-upload-action@v0.0.4
      with:
        id: 25712
        zipFilePath: Broker_DungeonDifficulty.zip
        compatible: 90001,80300,80205
        version: ${{ steps.get_versions.outputs.addon_version }}
        apiKey: ${{ secrets.WOW_INTERFACE }}
