name: Release to WoW Interface

on:
  workflow_dispatch:
    branches: [ master ]
  # push:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
  
    - name: Zip it good
      run: zip -9 -r Broker_CTA.zip Broker_CTA.lua Broker.lua Display.lua Localization.lua Broker_CTA.toc LICENSE README.md
      
#     - name: What is here (for debugging)
#       run: ls -lsa
      
    - name: Parse WoW Addon Verions
      id: get_versions
      uses: icbat/parse-wow-addon-version@v0.0.1
      with:
        tocfile:  Broker_CTA.toc
    
#     - name: Echo Verisons
#       run: echo ${{ steps.get_versions.outputs.supported_version }} ${{ steps.get_versions.outputs.addon_version }}

    - name: Upload to WoW Interface
      uses: icbat/wow-addon-upload-action@v0.0.4
      with:
        id: <<>>
        zipFilePath: Broker_CTA.zip
        compatible: 80300,80205,90000
        version: ${{ steps.get_versions.outputs.addon_version }}
        apiKey: ${{ secrets.WOW_INTERFACE }}
